### ISSUE TITLE
Empty cart on cancellation/refusal order

### ISSUE THREAD

**Issue by floorjubbega** [Adyen/adyen-shopware5#16] opened 2020-07-31 07:51 UTC
**Describe the bug**
After an order is cancelled or refused the cart is emptied within Shopware 5.
If the shopper would like to add an extra product to their cart from the checkout process, this can cause a bad user experience.

**To Reproduce**
1. Complete a transaction with incorrect cvc
2. Cart is emptied and shopper will have to add the items again

**Expected behavior**
Cart should have the items that were in the cart before the initial transaction attempt.

**Comment by runelaenen** [comment] 2020-08-13 12:16
Hello @floorjubbega 

I cannot reproduce your issue. Normally, the customer is redirected to the last page of the checkout again, and gets a notice that their payment was not successful.

The cart is rebuilt based on the old order, a new cart is generated automatically, and the checkout is loaded again using this new cart. The product should thus be automatically selected again.
This happens in \AdyenPayment\Components\BasketService::cancelAndRestoreByOrderNumber

Is it possible some custom code in your shop is interfering with the 'cart rebuild' logic of the Adyen plugin?

<img width="1287" alt="Screenshot 2020-08-13 at 14 13 56" src="https://user-images.githubusercontent.com/3930922/90133187-54151e80-dd6f-11ea-87c6-b88ac6984e04.png">

**Comment by danielDigitalArt** [comment] 2020-08-14 10:21
Hello @runelaenen ,

we reported this bug to Floor, we also tried to disable most plugins which might interfere in the checkout process but still the problem persists.

What we had was in the checkout we used the AMEX Credentials, while the account in the adyen backend does not allow adyen Cards. When we click on the buy button the shop loads and immediately goes back to the checkout window stating that the "payment details are not supported":
![Bildschirmfoto 2020-08-14 um 12 13 39](https://user-images.githubusercontent.com/25100967/90239606-188a5b00-de28-11ea-8ca3-94f8e34b4b92.png)

When i click to change the selected payment the system says that the cart is empty.

While the checkout got this error, i still got an email which says that the order was received, so i guess the problem is related to the case, where no matter hat payment of adyen is selected, it immediately processes the payment, even when the user did not set up any payment credentials whatsoever. Thus emptying the cart, because the order was already processed, but i never saw the order confirmation page.

**Comment by runelaenen** [comment] 2020-08-19 12:43
Hi @danielDigitalArt 

After a payment is cancelled and you are returned to Shopware, your old cart should be regenerated, based on the temporary order. This all happens in \AdyenPayment\Components\BasketService::restoreFromOrder. 

However, this means that you should not get an e-mail. When you receive an e-mail, that means that the order was accepted. This only happens when a notification from Adyen is received & processed, saying that the order was all OK.

I have tried reproducing the issue with your new information (using an amex card) but still cannot reproduce the issue. I'm going to forward this to a colleague of mine who can take a look too.

**Comment by danielDigitalArt** [comment] 2020-08-19 13:07
@runelaenen 
please be aware that i dont think it is specifically related to amex but the account that is connected will not allow amex-cards, so it will create the error message that you see above. Shopware itself then still contiues to process the order and thus empties the cart, which would explain the behavior from the first post.

**Comment by runelaenen** [comment] 2020-08-20 11:45
#12 seems to describe the same issue, however, as you can see in the video screencap I've posted there, the bug does not occur on my 'empty' shopware installation.
I'm still asking my colleague to take a look at it. Maybe he can spot something that I don't.

**Comment by acampos1916** [comment] 2021-02-26 14:42
Hello all,

After some fixes to the way we received the parameters from redirect payment methods and how the order is restored after a failed payment looks like this isn't an issue anymore. I will close this issue now but feel free to comment with ways to reproduce it if encountered again.

Best,
Ángel

**Closed by acampos1916** 2021-02-26 14:42 UTC
